### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by Widixo** [Upipe/upipe#630]
libav 9.10 shared and pic. same with libav 12.

In file included from upipe_sws.c:48:0:
../../include/upipe-av/upipe_av_pixfmt.h: In function ‘upipe_av_pixfmt_to_flow_def’:
../../include/upipe-av/upipe_av_pixfmt.h:208:14: error: ‘AV_PIX_FMT_RGBA64BE’ undeclared (first use in this function)
         case AV_PIX_FMT_RGBA64BE:
              ^
../../include/upipe-av/upipe_av_pixfmt.h:208:14: note: each undeclared identifier is reported only once for each function it appears in
../../include/upipe-av/upipe_av_pixfmt.h: In function ‘upipe_av_pixfmt_from_flow_def’:
../../include/upipe-av/upipe_av_pixfmt.h:265:9: error: ‘AV_PIX_FMT_RGBA64BE’ undeclared (first use in this function)
         AV_PIX_FMT_RGBA64BE,
         ^
In file included from upipe_sws_thumbs.c:47:0:
../../include/upipe-av/upipe_av_pixfmt.h: In function ‘upipe_av_pixfmt_to_flow_def’:
../../include/upipe-av/upipe_av_pixfmt.h:208:14: error: ‘AV_PIX_FMT_RGBA64BE’ undeclared (first use in this function)
         case AV_PIX_FMT_RGBA64BE:
              ^
../../include/upipe-av/upipe_av_pixfmt.h:208:14: note: each undeclared identifier is reported only once for each function it appears in
../../include/upipe-av/upipe_av_pixfmt.h: In function ‘upipe_av_pixfmt_from_flow_def’:
../../include/upipe-av/upipe_av_pixfmt.h:265:9: error: ‘AV_PIX_FMT_RGBA64BE’ undeclared (first use in this function)
         AV_PIX_FMT_RGBA64BE,
         ^
make[3]: *** [libupipe_swscale_la-upipe_sws_thumbs.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [libupipe_swscale_la-upipe_sws.lo] Error 1
make[3]: Leaving directory `/home/cedric/install/upipe-0.5/lib/upipe-swscale'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/home/cedric/install/upipe-0.5/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/cedric/install/upipe-0.5'
make: *** [all] Error 2

**Comment by Widixo** [comment]
sorry, finaly works with ffmpeg 2.8

**Comment by kierank** [comment]
Use less ancient ffmpeg :)
